### GET or CREATE a reader
GET http://localhost:5000/api/reader/670c963388ce4da4c956dbf7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDdlN2I0MTY5N2YzZTU5M2YyOTYwMCIsInJvbGUiOlsidXNlciJdLCJpYXQiOjE3MjkzMDg0NDUsImV4cCI6MTcyOTMxNTY0NX0.k2nTNxw7O9MqgsbOq2p9HfP7wXyFyJLhpuYUp8nC_4A

### CREATE or UPDATE a reader
POST http://localhost:5000/api/reader/670c963388ce4da4c956dbf7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MDdlN2I0MTY5N2YzZTU5M2YyOTYwMCIsInJvbGUiOlsidXNlciJdLCJpYXQiOjE3Mjg4NzcyNDIsImV4cCI6MTcyODg4NDQ0Mn0.cd_84k_TrW7NbnJ7LWOUrTYrwUW4DUQMW5VydT8HKWA
Content-Type: application/json

{
  "currentLocation": {
    "chapterName": "Introduction",
    "currentPage": 5,
    "totalPage": 1,
    "startCfi": "epubcfi(/6/2[cover]!/6)",
    "endCfi": "epubcfi(/6/2[cover]!/6)",
    "base": "epubcfi(/6/2/)"
  }
}
